<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>
<?php
$allowedCountries = explode(",",$block->getAllowedCountries());
?>
<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('telephone')
            );
        ?>
        <div class="phoneArea" style="min-height: 40px;">
            <div class="encloser">
                <select id="countryPhoneCode">
                    <?php
                    foreach($allowedCountries as $countryCode){
                        $countryInformation = $block->getCountryInformation($countryCode);
                        ?><option data-phone-code="+<?= $countryInformation['phone'][0] ?>" value="<?php echo $countryCode; ?>"><?php echo /*__($countryInformation['name']) .*/'+'. $countryInformation['phone'][0];?></option><?php
                    }
                    ?>
                </select>
              </div>
              <?php
              foreach($allowedCountries as $countryCode){
                  $countryInformation = $block->getCountryInformation($countryCode);
                  ?>
                  <input type="text"
                         id="localTelephoneNumber"
                         value="<?= $block->escapeHtmlAttr($block->getLocalTelephone()) ?>"
                         title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                         class="localTelephoneNumber input-text phone-length-<?= $countryCode ?> <?= $_validationClass ?: '' ?>">
                  <?php
              }
              ?>
        </div>
        <input type="hidden"
               name="telephone"
               id="telephone"
               value=""
               class="input-text"
        >
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'mage/translate', 'jquery/ui', 'jquery/validate'], function($, $t){
        $(document).ready( function() {
            $('#countryPhoneCode > option').each(function() {
                var countryCode = $(this).val();
                countryPhoneLengthMessage = '';
                if(countryCode == 'SA'){ // Saudi Arabia
                    countryPhoneLengthMessage = '9';
                } else if (countryCode == 'BH'){ // Bahrain
                    countryPhoneLengthMessage = '8';
                } else if (countryCode == 'AE'){ // United Arab Emirates
                    countryPhoneLengthMessage = '9';
                } else if (countryCode == 'KW'){ // Kuwait
                    countryPhoneLengthMessage = '8';
                } else if (countryCode == 'OM'){ // Oman
                    countryPhoneLengthMessage = '8';
                } else if (countryCode == 'IQ'){ // Iraq
                    countryPhoneLengthMessage = '10';
                } else if (countryCode == 'QA'){ // Qatar
                    countryPhoneLengthMessage = '8';
                }
                $.validator.addMethod(
                    'phone-length-'+countryCode , function (value) {
                    if(countryCode == 'SA'){ // Saudi Arabia
                        if( value.length == 9 ){
                            return true;
                        }else{
                            return false;
                        }
                    } else if (countryCode == 'BH'){ // Bahrain
                        if( value.length == 8 ){
                            return true;
                        }else{
                            return false;
                        }
                    } else if (countryCode == 'AE'){ // United Arab Emirates
                        if( value.length == 9 ){
                            return true;
                        }else{
                            return false;
                        }
                    } else if (countryCode == 'KW'){ // Kuwait
                        if( value.length == 8 ){
                            return true;
                        }else{
                            return false;
                        }
                    } else if (countryCode == 'OM'){ // Oman
                        if( value.length == 8 ){
                            return true;
                        }else{
                            return false;
                        }
                    } else if (countryCode == 'IQ'){ // Iraq
                        if( value.length == 10 ){
                            return true;
                        }else{
                            return false;
                        }
                    } else if (countryCode == 'QA'){ // Qatar
                        if( value.length == 8 ){
                            return true;
                        }else{
                            return false;
                        }
                    }
                }, $t('Phone number is exactly %s digits.').replace('%s', countryPhoneLengthMessage));
            });

            function validatePhone(element){
              console.log('validate ****');
              var localPhoneNumber = element.val();
              var localPhoneNumberArray = localPhoneNumber.split('');
              var outputlocalPhoneNumberArray = [];
              $.each(localPhoneNumberArray, function( index, value ) {
                  if((value === "0" || value === "٠") && outputlocalPhoneNumberArray.length == 0){
                  } else if (value === "٠"){
                      outputlocalPhoneNumberArray.push("0");
                  } else if (value === "١"){
                      outputlocalPhoneNumberArray.push("1");
                  } else if (value === "٢"){
                      outputlocalPhoneNumberArray.push("2");
                  } else if (value === "٣"){
                      outputlocalPhoneNumberArray.push("3");
                  } else if (value === "٤"){
                      outputlocalPhoneNumberArray.push("4");
                  } else if (value === "٥"){
                      outputlocalPhoneNumberArray.push("5");
                  } else if (value === "٦"){
                      outputlocalPhoneNumberArray.push("6");
                  } else if (value === "٧"){
                      outputlocalPhoneNumberArray.push("7");
                  } else if (value === "٨"){
                      outputlocalPhoneNumberArray.push("8");
                  } else if (value === "٩"){
                      outputlocalPhoneNumberArray.push("9");
                  } else if(value === "0" || value === "1" || value === "2" || value === "3" || value === "4" || value === "5" || value === "6" || value === "7" || value === "8" || value === "9"){
                      outputlocalPhoneNumberArray.push(value);
                  } else {
                      // do nothing
                  }
              });
              var outputlocalPhoneNumber = outputlocalPhoneNumberArray.join("");
              $('.localTelephoneNumber').val(outputlocalPhoneNumber);
            }
            function registerPhone(){
              var phoneCode = $('#countryPhoneCode').find(":selected").data('phone-code');
              var localPhoneNumber = $('.localTelephoneNumber:visible').val();
              var internationalPhoneNumber = phoneCode + localPhoneNumber;
              $('#telephone').val(internationalPhoneNumber);
            }

            $("#country").change(function () {
                var end = this.value;
                $("#countryPhoneCode").val(end).change();
            });
            $("#countryPhoneCode").change(function () {
                $('#localTelephoneNumber-error').appendTo($('#localTelephoneNumber-error').parent().first());
                var end = this.value;
                $('.localTelephoneNumber').hide();
                $('.localTelephoneNumber.phone-length-'+end).show();

            });



            // $("#countryPhoneCode").change();

            $(".localTelephoneNumber").on('change keydown paste input', function(){
                validatePhone($(this));
                registerPhone();
            });
            $('.localTelephoneNumber').each(function() {
                validatePhone($(this));
            });
            registerPhone();

            if($('#country').val()){
                $("#countryPhoneCode").val($('#country').val()).change();
            } else {
                $("#countryPhoneCode").val('<?= $block->escapeHtmlAttr($block->getDefaultCountry()) ?>').change();
            }


        });
    });
</script>
<style type="text/css">
    .phoneArea select {
        width: 140px;
        box-shadow: unset !important;
        pointer-events: none;
        border: unset;
    }
    .phoneArea input {
      	width: calc(100% - 100px);
        display: inline-block;
    }
    .phoneArea .encloser {
      	width: 100px;
      	display: inline-block;
      	float: left;
      	overflow: hidden;
      	border: 1px solid #ccc;
      	height: 40px;
      	border-right: 0;
    }
    .phoneArea {
    	margin-bottom: 24px;
    	position: relative;
    }
    .phoneArea div.mage-error {
    	position: absolute;
    	top: 38px;
    }
</style>
